language: cpp
sudo: required
compiler: gcc

script:
 - docker-compose build $TEST_ENV
 - docker run --rm -ti scala-native-bindgen:$TEST_ENV /usr/include/ctype.h -name ctype --
 - docker-compose run --rm sbt-test

matrix:
  include:
  - env: TEST_ENV=ubuntu-16.04-llvm-dev
  - env: TEST_ENV=ubuntu-16.04-llvm-6.0
  - env: TEST_ENV=ubuntu-16.04-llvm-5.0
