language: cpp
sudo: required
compiler: gcc

script:
 - docker-compose build $TEST_ENV
 - docker-compose run $TEST_ENV

matrix:
  include:
  - env: TEST_ENV=ubuntu-18.04-llvm-dev
  - env: TEST_ENV=ubuntu-18.04-llvm-6.0
  - env: TEST_ENV=ubuntu-18.04-llvm-5.0
